# Generated by Django 5.2.8 on 2025-11-25 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('action', 'Acción'), ('adventure', 'Aventura'), ('comedy', 'Comedia'), ('drama', 'Drama'), ('fantasy', 'Fantasía'), ('horror', 'Terror'), ('sci-fi', 'Ciencia Ficción'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('animation', 'Animación'), ('documentary', 'Documental'), ('other', 'Otro')], max_length=20)),
                ('poster_url', models.URLField(blank=True, max_length=500)),
                ('imdb_id', models.CharField(blank=True, max_length=20)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_date'],
            },
        ),
    ]
