# Generated by Django 5.2.8 on 2025-11-25 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-added_date'], 'verbose_name': 'Película', 'verbose_name_plural': 'Películas'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agregado por'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de agregado'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=100, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'Acción'), ('adventure', 'Aventura'), ('comedy', 'Comedia'), ('drama', 'Drama'), ('fantasy', 'Fantasía'), ('horror', 'Terror'), ('sci-fi', 'Ciencia Ficción'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('animation', 'Animación'), ('documentary', 'Documental'), ('other', 'Otro')], max_length=20, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID de IMDB'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL del Poster'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(verbose_name='Año de estreno'),
        ),
    ]
