# Generated by Django 5.2.8 on 2025-11-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0002_alter_movie_options_alter_movie_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdbRating',
            field=models.IntegerField(default=0.0, verbose_name='Puntuación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Acción'), ('Adventure', 'Aventura'), ('Comedy', 'Comedia'), ('Drama', 'Drama'), ('Fantasy', 'Fantasía'), ('Horror', 'Terror'), ('Sci-fi', 'Ciencia Ficción'), ('Thriller', 'Thriller'), ('Romance', 'Romance'), ('Animation', 'Animación'), ('Documentary', 'Documental'), ('Other', 'Otro')], max_length=200, verbose_name='Género'),
        ),
    ]
