# Generated by Django 5.2.8 on 2025-11-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0003_movie_imdbrating_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdbRating',
            field=models.IntegerField(blank=True, max_length=20, verbose_name='Puntuación'),
        ),
    ]
