# Generated by Django 5.2.8 on 2025-11-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0004_alter_movie_imdbrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imdbRating',
        ),
    ]
